#platform :ios, '11.0'

use_frameworks!

target 'Hold' do

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Parse'

  target 'HoldTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
